# Generated by Django 2.2.12 on 2023-06-09 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('prodName', models.CharField(max_length=100)),
                ('prodDesc', models.TextField()),
                ('image', models.URLField()),
                ('sideImg', models.URLField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quant', models.PositiveIntegerField()),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('category', models.CharField(max_length=50)),
                ('custName', models.CharField(max_length=100)),
                ('vendorName', models.CharField(max_length=100)),
                ('tags', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prodName', models.CharField(max_length=100)),
                ('prodDesc', models.TextField()),
                ('image', models.URLField()),
                ('sideImg', models.URLField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quant', models.PositiveIntegerField()),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('category', models.CharField(max_length=50)),
                ('custName', models.CharField(max_length=100)),
                ('vendorName', models.CharField(max_length=100)),
                ('tags', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('rating', models.IntegerField(default=0)),
                ('content', models.CharField(max_length=50)),
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('createdAt', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=20)),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
