# Generated by Django 4.2.2 on 2023-06-16 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_shoppieuser_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
    ]
