# Generated by Django 4.2.2 on 2023-06-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_shoppieuser_password_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppieuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='shoppieuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='shoppieuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='shoppieuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='shoppieuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='shoppieuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='shoppieuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='shoppieuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='shoppieuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='shoppieuser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='shoppieuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='shoppieuser',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='The users belonging to this group.', related_name='my_groups', to='myapp.shoppieuser', verbose_name='users'),
        ),
        migrations.AlterField(
            model_name='shoppieuser',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shoppieuser',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
