# Generated by Django 4.2.2 on 2023-06-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_shoppieuser_options_alter_shoppieuser_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='content',
        ),
        migrations.RemoveField(
            model_name='review',
            name='createdAt',
        ),
        migrations.AddField(
            model_name='review',
            name='author',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='comment',
            field=models.TextField(default='good'),
        ),
        migrations.AddField(
            model_name='review',
            name='product_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
